sudo: required

services:
  - docker 

before_install: 
  - docker build -t marcionedes/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true  marcionedes/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-806294794245"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 
